services:
  - type: web
    name: idcultural-app
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: id-cultural-db
          property: connectionString

databases:
  - name: id-cultural-db
    plan: free
