services:
  - type: web
    name: idcultural-app
    runtime: php
    plan: free
    buildCommand: ""   
    startCommand: php -S 0.0.0.0:10000 -t .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: id-cultural-db
          property: connectionString

databases:
  - name: id-cultural-db
    plan: free
